version: '3.8'

services:
  nas:
    image: dummy/nas:latest
    container_name: ${PROJECT_NAME}_nas
    restart: unless-stopped
    ports:
      - "${NAS_PORT}:80"
    environment:
      - SERVICE_NAME=nas
      - ACCESS_TOKEN=${NAS_ACCESS_TOKEN}
      - DATABASE_URL=postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@database:${DATABASE_PORT}/${DATABASE_NAME}
    env_file:
      - ../../../config/common.env
      - ../../../secrets/.env
    networks:
      - backend
    volumes:
      - shared_data:/app/data
      - secrets:/app/secrets:ro
      - nas_data:/app/nas
      - backup_data:/app/backups
    depends_on:
      - database
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'

volumes:
  shared_data:
    external: true
  secrets:
    external: true
  nas_data:
    external: true
  backup_data:
    external: true

networks:
  backend:
    external: true 