version: '3.8'

services:
  loadbalancer:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_loadbalancer
    restart: unless-stopped
    ports:
      - "${LOADBALANCER_PORT}:80"
    environment:
      - SERVICE_NAME=loadbalancer
      - LOADBALANCER_ALGORITHM=${LOADBALANCER_ALGORITHM}
      - HEALTH_CHECK_INTERVAL=${HEALTH_CHECK_INTERVAL}
      - HEALTH_CHECK_TIMEOUT=${HEALTH_CHECK_TIMEOUT}
    env_file:
      - ../../../config/common.env
      - ../../../secrets/.env
    networks:
      - infrastructure
      - frontend
      - backend
    volumes:
      - loadbalancer_data:/etc/nginx
      - secrets:/app/secrets:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  loadbalancer_data:
    external: true
  secrets:
    external: true

networks:
  infrastructure:
    external: true
  frontend:
    external: true
  backend:
    external: true 